alias vi=nvim
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000

alias python=python3
alias pip=pip3


export PATH="${PATH}:${HOME}/bin:$HOME/.local/bin"

if command -v ngrok &>/dev/null; then
    eval "$(ngrok completion)"
fi

